networks:
  traefik:
    external: true

services:
  website:
    container_name: fullcontrolmtg-website
    build: .
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.fullcontrolmtg.rule=Host(`fullcontrol.whitney.rip`)"
      - "traefik.http.routers.fullcontrolmtg.entrypoints=websecure"
      - "traefik.http.routers.fullcontrolmtg.tls=true"
      - "traefik.http.routers.fullcontrolmtg.tls.certresolver=letsencrypt"
      - "traefik.http.services.fullcontrolmtg.loadbalancer.server.port=3000"
